version: "3.3"

services:
  apache:
    build:
      context: .
      args:
        - "PROXY_USER=user1"
        - "PROXY_PASSWORD=nygZMR3z2djB8sJCInFP"
    restart: always
    ports:
      - 4581:80
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"
